### ISSUE TITLE
Temporal resolution of start datetime

### ISSUE THREAD

**Issue by kthyng** [NOAA-ORR-ERD/LibGOODS#27]
@ChrisBarker-NOAA When you query a model for the available time range, do you just want the start date or do you also want the specific time of the first available file on that date? On the end date it is more complicated for forecast files since the forecast hours push out the date and have to be checked regardless, therefore not searching for the time won't save any computation time.

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- I would think it should be a full datetime -- there's a big difference between 0000hours and 2300 after all. And with timezones, it can get weird.

-CHB

**Comment by kthyng** [comment]
ok, thanks!
